package nox.plugin

import nox.compiler.types.CallTarget
import nox.compiler.types.NoxParam
import nox.compiler.types.TypeRef
import nox.plugin.annotations.*
import nox.plugin.external.NoxPluginManifest
import nox.plugin.external.NoxTypeTag
import java.util.ServiceLoader

/**
 * Central compile-time and runtime registry for all plugin functions.
 *
 * A dynamically populated registry driven by annotations (`@NoxModule`, `@NoxFunction`, `@NoxTypeMethod`)
 * and external plugin manifests.
 *
 * **Registration flow:**
 * 1. `PluginRegistryProvider` (generated by KSP) instances are discovered via `ServiceLoader`.
 * 2. `registerExternalPlugin(manifest)` registers Tier 1 compile-time signatures.
 * 3. `createDefault()` registers all stdlib modules.
 *
 * **Query API** (used by the compiler during semantic analysis):
 * - `isBuiltinNamespace(name)`: check namespace existence
 * - `lookupNamespaceFunc(namespace, funcName)`: resolve namespace function
 * - `lookupBuiltinMethod(targetType, methodName)`: resolve type-bound method
 * - `lookupTypeMethod(targetType, methodName)`: resolve conversion method
 *
 * **Runtime API** (used by the VM during SCALL dispatch):
 * - `lookupNativeFunc(scallName)`: get the linked NoxNativeFunc adapter
 *
 * See docs/extensibility/plugin-guide.md for the full architecture.
 */
class LibraryRegistry {
    // Compile-time data (CallTargets for semantic analysis)
    private val namespaceFunctions = mutableMapOf<String, MutableMap<String, CallTarget>>()
    private val builtinMethods = mutableMapOf<String, MutableMap<String, CallTarget>>()
    private val typeMethods = mutableMapOf<String, MutableMap<String, CallTarget>>()
    private val arrayMethodNames = mutableSetOf("push", "pop", "length")

    private data class TemplateSignature(
        val genericParams: List<String>,
        val baseScallName: String,
        val targetTypeStr: String?,
        val methodName: String,
        val namespace: String?,
        val callTargetBuilder: (Map<String, TypeRef>) -> CallTarget,
        val nativeFuncBuilder: (Map<String, TypeRef>) -> NoxNativeFunc,
    )

    private val templates = mutableListOf<TemplateSignature>()

    // Runtime data (NoxNativeFuncs for VM SCALL dispatch)
    private val nativeFuncs = mutableMapOf<String, NoxNativeFunc>()

    // Tier 1 namespace tracking
    private val _externalPluginNamespaces = mutableSetOf<String>()

    /** All built-in (Tier 0) namespace names. */
    val builtinNamespaceNames: Set<String> get() = namespaceFunctions.keys

    /** All external (Tier 1) plugin namespace names. */
    val externalPluginNamespaces: Set<String> get() = _externalPluginNamespaces

    /** Whether [name] is a built-in (Tier 0) or external (Tier 1) namespace. */
    fun isBuiltinNamespace(name: String): Boolean = name in namespaceFunctions || name in _externalPluginNamespaces

    /** All function names registered under [namespace], for completion enumeration. */
    fun getNamespaceFunctionNames(namespace: String): Set<String> = namespaceFunctions[namespace]?.keys.orEmpty()

    /** All [CallTarget]s registered under [namespace], for completion and signature-help rendering. */
    fun getNamespaceFunctions(namespace: String): Map<String, CallTarget> = namespaceFunctions[namespace].orEmpty()

    /** Look up a namespace function by [namespace] and [funcName]. */
    fun lookupNamespaceFunc(
        namespace: String,
        funcName: String,
    ): CallTarget? {
        namespaceFunctions[namespace]?.get(funcName)?.let { return it }

        // Template match
        for (template in templates) {
            if (template.namespace == namespace && template.methodName == funcName) {
                // Not yet fully supported for standalone namespace generics unless type inferences exist
                // but we can return null for now if they aren't instantiated explicitly.
            }
        }
        return null
    }

    /**
     * Look up a built-in method on [targetType] (e.g. `string.upper()`, `arr.length()`).
     */
    fun lookupBuiltinMethod(
        targetType: TypeRef,
        methodName: String,
    ): CallTarget? {
        // Direct type match (e.g. string.upper(), json.size())
        builtinMethods[targetType.toString()]?.get(methodName)?.let { return it }
        // Struct types can call json methods (implicit upcast)
        if (targetType.isStructType()) {
            builtinMethods["json"]?.get(methodName)?.let { return it }
        }

        // Template match
        for (template in templates) {
            if (template.targetTypeStr != null && template.methodName == methodName) {
                val mapping = targetType.match(template.targetTypeStr)
                if (mapping != null) {
                    return template.callTargetBuilder(mapping)
                }
            }
        }
        return null
    }

    /** Look up a type-bound conversion method (e.g. `int.toDouble()`). */
    fun lookupTypeMethod(
        targetType: TypeRef,
        methodName: String,
    ): CallTarget? = typeMethods[targetType.toString()]?.get(methodName)

    /** All built-in method names for [targetType] (for diagnostics). */
    fun getBuiltinMethodNames(targetType: TypeRef): Set<String>? {
        val names = mutableSetOf<String>()
        builtinMethods[targetType.toString()]?.keys?.let { names.addAll(it) }
        if (targetType.isStructType()) builtinMethods["json"]?.keys?.let { names.addAll(it) }
        for (template in templates) {
            if (template.targetTypeStr != null && targetType.match(template.targetTypeStr) != null) {
                names.add(template.methodName)
            }
        }
        return names.ifEmpty { null }
    }

    /** All type-bound conversion method names for [targetType] (for diagnostics). */
    fun getTypeMethodNames(targetType: TypeRef): Set<String>? = typeMethods[targetType.toString()]?.keys

    /** Look up a linked native function by SCALL name (for VM dispatch). */
    fun lookupNativeFunc(scallName: String): NoxNativeFunc? {
        nativeFuncs[scallName]?.let { return it }
        if (!scallName.contains("!")) return null

        // JIT Linking for Generics
        val parts = scallName.split("!")
        val baseName = parts[0]
        val template = templates.find { it.baseScallName == baseName } ?: return null
        val mapping = template.genericParams.zip(parts.drop(1).map { parseTypeRefString(it) }).toMap()

        val linked = template.nativeFuncBuilder(mapping)
        nativeFuncs[scallName] = linked
        return linked
    }

    /**
     * Register a namespace function. Designed to be called by KSP-generated code.
     */
    fun registerFunction(
        namespace: String,
        noxName: String,
        callTarget: CallTarget,
        nativeFunc: NoxNativeFunc,
    ) {
        val funcMap = namespaceFunctions.getOrPut(namespace) { mutableMapOf() }
        funcMap[noxName] = callTarget
        nativeFuncs[callTarget.name] = nativeFunc
    }

    /**
     * Register a type-bound method. Designed to be called by KSP-generated code.
     */
    fun registerTypeMethod(
        targetTypeStr: String,
        noxName: String,
        isConversionMethod: Boolean,
        callTarget: CallTarget,
        nativeFunc: NoxNativeFunc,
    ) {
        val targetMap =
            if (isConversionMethod) {
                typeMethods.getOrPut(targetTypeStr) { mutableMapOf() }
            } else {
                builtinMethods.getOrPut(targetTypeStr) { mutableMapOf() }
            }

        targetMap[noxName] = callTarget
        nativeFuncs[callTarget.name] = nativeFunc
    }

    /**
     * Register a template generic method/function. Designed to be called by KSP-generated code.
     */
    fun registerTemplate(
        genericParams: List<String>,
        baseScallName: String,
        targetTypeStr: String?,
        methodName: String,
        namespace: String?,
        callTargetBuilder: (Map<String, TypeRef>) -> CallTarget,
        nativeFuncBuilder: (Map<String, TypeRef>) -> NoxNativeFunc,
    ) {
        templates.add(
            TemplateSignature(
                genericParams,
                baseScallName,
                targetTypeStr,
                methodName,
                namespace,
                callTargetBuilder,
                nativeFuncBuilder,
            ),
        )
    }

    /**
     * Register a Tier 1 (external C ABI) plugin manifest.
     *
     * Registers compile-time signatures only. The actual native function
     * pointers are managed by the native bridge.
     */
    fun registerExternalPlugin(manifest: NoxPluginManifest) {
        _externalPluginNamespaces.add(manifest.namespace)
        val funcMap = namespaceFunctions.getOrPut(manifest.namespace) { mutableMapOf() }

        for (func in manifest.functions) {
            val params =
                func.paramTypes.mapIndexed { i, tag ->
                    NoxParam("arg$i", typeTagToTypeRef(tag))
                }
            funcMap[func.name] =
                CallTarget("${manifest.namespace}__${func.name}", params, typeTagToTypeRef(func.returnType))
        }
    }

    /** Register a runtime adapter directly (used by ExternalPluginBridge) */
    fun registerNativeFunc(
        scallName: String,
        func: NoxNativeFunc,
    ) {
        nativeFuncs[scallName] = func
    }

    companion object {
        /**
         * Create a [LibraryRegistry] by auto-discovering all `PluginRegistryProvider`
         * implementations using `ServiceLoader`.
         */
        fun createDefault(): LibraryRegistry {
            val registry = LibraryRegistry()
            val providers = ServiceLoader.load(PluginRegistryProvider::class.java)
            for (provider in providers) {
                provider.registerAll(registry)
            }
            return registry
        }

        /** Map a [NoxTypeTag] to a Nox [TypeRef]. */
        fun typeTagToTypeRef(tag: NoxTypeTag): TypeRef =
            when (tag) {
                NoxTypeTag.INT -> TypeRef.INT
                NoxTypeTag.DOUBLE -> TypeRef.DOUBLE
                NoxTypeTag.BOOLEAN -> TypeRef.BOOLEAN
                NoxTypeTag.STRING -> TypeRef.STRING
                NoxTypeTag.JSON -> TypeRef.JSON
                NoxTypeTag.VOID -> TypeRef.VOID
                NoxTypeTag.STRING_ARRAY -> TypeRef("string", 1)
                NoxTypeTag.INT_ARRAY -> TypeRef("int", 1)
                NoxTypeTag.DOUBLE_ARRAY -> TypeRef("double", 1)
            }

        /**
         * Parse a type string like "int", "string[]", "double[]" to a [TypeRef].
         */
        fun parseTypeRefString(typeStr: String): TypeRef {
            var name = typeStr
            var depth = 0
            while (name.endsWith("[]")) {
                name = name.removeSuffix("[]")
                depth++
            }
            return TypeRef(name, depth)
        }

        /** Whether a method name looks like a conversion (toX, fromX). */
        fun isConversionLike(name: String): Boolean =
            (name.startsWith("to") && name.length > 2 && name[2].isUpperCase()) ||
                (name.startsWith("from") && name.length > 4 && name[4].isUpperCase())
    }
}
